# Generated by Django 4.2 on 2023-12-19 18:05

from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations, models
import django.db.models.deletion

from api.models import Question


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def create_question_models(apps, schema_manager):
        """
        Creates the room booking models table.
        """
        apps.create_model('api_question', 'Question', (
            'id', models.AutoField(primary_key=True),
            'user', models.ForeignKey(User, on_delete=models.CASCADE),
            'question_text', models.TextField(unique=True),
            'date', models.DateTimeField(auto_now_add=True),
            'like', models.IntegerField(default=0),
            'comment', models.IntegerField(default=0),
            'hashtag', models.CharField(max_length=255),
        )),

    def create_answer_models(apps, schema_manager):
        """
        Creates the room booking models table.
        """
        apps.create_model('api_answer', 'Answer', (
            'user', models.ForeignKey(User, on_delete=models.CASCADE),
            'quests_text', models.ForeignKey(Question, on_delete=models.PROTECT, db_constraint=True),
            'answer_text', models.TextField(),
            'date', models.DateTimeField(auto_now_add=True),
        )),
