# Generated by Django 4.2 on 2023-12-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_answer_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
